# Generated by Django 5.1.5 on 2025-01-21 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('Entity', 'ENTITY'), ('Activity', 'ACTIVITY'), ('Agent', 'AGENT'), ('Bundle', 'BUNDLE'), ('Collection', 'COLLECTION'), ('Organization', 'ORGANIZATION'), ('Person', 'PERSON'), ('SoftwareAgent', 'SOFTWARE_AGENT'), ('Plan', 'PLAN'), ('PrimarySource', 'PRIMARY_SOURCE'), ('Revision', 'REVISION'), ('Quotation', 'QUOTATION')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['node_type'], name='provenance__node_ty_30be1a_idx'), models.Index(fields=['label'], name='provenance__label_829f9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProvRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.CharField(choices=[('wasGeneratedBy', 'WAS_GENERATED_BY'), ('wasAttributedTo', 'WAS_ATTRIBUTED_TO'), ('wasAssociatedWith', 'WAS_ASSOCIATED_WITH'), ('used', 'USED'), ('actedOnBehalfOf', 'ACTED_ON_BEHALF_OF'), ('wasInformedBy', 'WAS_INFORMED_BY'), ('wasDerivedFrom', 'WAS_DERIVED_FROM'), ('wasRevisionOf', 'WAS_REVISION_OF'), ('wasQuotedFrom', 'WAS_QUOTED_FROM'), ('hadPrimarySource', 'HAD_PRIMARY_SOURCE'), ('wasStartedBy', 'WAS_STARTED_BY'), ('wasEndedBy', 'WAS_ENDED_BY'), ('invalidatedBy', 'INVALIDATED_BY'), ('wasInvalidatedBy', 'WAS_INVALIDATED_BY')], max_length=50)),
                ('run_id', models.CharField(blank=True, db_index=True, help_text='Client-provided identifier for sorting and grouping relations', max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_object', to='provenance.provnode')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_subject', to='provenance.provnode')),
            ],
            options={
                'indexes': [models.Index(fields=['verb'], name='provenance__verb_125e3e_idx'), models.Index(fields=['subject', 'verb'], name='provenance__subject_316d9d_idx'), models.Index(fields=['object', 'verb'], name='provenance__object__5fda70_idx'), models.Index(fields=['run_id', '-created_at'], name='prov_relation_run_created')],
            },
        ),
    ]
